version: '2.1'

services:
  localstack:
    container_name: "dynamo-poc"
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "8080:8080"
    environment:
      - SERVICES=dynamodb,dynamodbstreams